[package]
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>", "Yuji Kanagawa <yuji.kngw.80s.revive@gmail.com>"]
description = "Rust binding of NumPy C-API"
documentation = "https://pyo3.github.io/rust-numpy/numpy"
edition = "2018"
keywords = ["numpy", "python", "binding"]
license-file = "LICENSE"
name = "numpy"
repository = "https://github.com/rust-numpy/rust-numpy"
version = "0.13.0"

[dependencies]
cfg-if = "0.1"
libc = "0.2"
ndarray = "0.14"
num-complex = "0.3"
num-traits = "0.2"
pyo3 = {version = "0.13", default-features = false}

[features]
# In default setting, python version is automatically detected
default = []
rayon = ["ndarray/rayon"]

[workspace]
members = ["examples/*"]
